apiVersion: v1
kind: Service
metadata:
  name: result
  labels:
    name: result-label
    
spec:
  type: NodePort
  ports:
    - port : 80
      targetPort: 80
      nodePort: 30004
  selector:
     app: voting-app-pod-js

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: voting-app-deploy-js
  labels:
    app: js
spec:
  replicas: 1
  selector:
    matchLabels:
      app: voting-app-pod-js
  template:
    metadata:
      labels:
        app: voting-app-pod-js
    spec:
      containers:
        - name: voting-app-container
          image: kodekloud/examplevotingapp_result:v1
          ports:
            - containerPort: 80